inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

inherit_mode:
  merge:
    - Exclude

CodeReuse/ActiveRecord:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - "gemfiles/**/*"

RSpec/MultipleMemoizedHelpers:
  Max: 10
